### ISSUE TITLE
Possible to use multiple sources?

### ISSUE THREAD

**Issue by davidrhoderick** [t-obi/react-video-cover#206]
The HTML `<video>` tag allows for using multiple child `<source>` tags so that you can provide various formats of videos so that the video renders best on the browser being used (not just MP4 but also ogg/ogv and WebM).  Is there a way to use these multiple sources?

**Comment by tkloht** [comment]
yes, it is possible.
the `videoOptions` are passed as props to the video tag, so you can do something like this:

``` js
<VideoCover videoOptions = {{
      children: [
        <source src={'/cat.mp4')} />,
        <source src={'/cat.ogv')} />,
        <source src={'/cat.webm')} />
      ]
}} />
```

**Comment by davidrhoderick** [comment]
Thanks that worked great @tkloht
